In [2]:
import numpy as np

In [17]:
my_array = np.array([1,10,-5,20])
my_array

array([ 1, 10, -5, 20])

In [18]:
print(f"The means is {my_array.mean()}")
print(f"The means is {my_array.std()}")


The means is 6.5
The means is 9.447221813845593
The means is 9.447221813845593


In [19]:
print(f"Multiplication by 2 {my_array*2}")

Multiplication by 2 [  2  20 -10  40]


In [21]:
my_arr_4x3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [26]:
my_arr_4x3 *4



array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [27]:
my_arr_4x3.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [35]:
print (f" this is transposed:\n {my_arr_4x3.T}")

 this is transposed:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [36]:
print (f" this is coposed by:\n {my_arr_4x3.size}")

 this is coposed by:
 12


In [37]:
print (f" this is a matrics of by:\n {my_arr_4x3.shape}")

 this is coposed by:
 (4, 3)


In [80]:
random_integers = np.random.randint(100,200,20) # in quesot modo genera 20 numeri in array tra 100 e 200
random_integers

array([105, 168, 145, 149, 162, 117, 148, 168, 154, 110, 177, 105, 147,
       121, 108, 135, 162, 190, 167, 119])

In [89]:
even_numbers = random_integers[random_integers % 2 == 0]
even_numbers

array([168, 162, 148, 168, 154, 110, 108, 162, 190])

In [94]:
sliced_array = even_numbers[2:8]
sliced_array

array([148, 168, 154, 110, 108, 162])

In [105]:
arr1 = np.random.randint (0,10,4)
arr2 = np.random.randint (0,10,4)
print (f"/ the 2 arrays are: \n {arr1}, \n {arr2}")

/ the 2 arrays are: 
 [8 7 9 5], 
 [1 5 4 5]


In [106]:
print (f"\ the sum of the 2 arrays is: \n {arr1+arr2} , \n and the difference is: \n {arr1-arr2}, \n and the multiplication is: \n {arr1*arr2}")

\ the sum of the 2 arrays is: 
 [ 9 12 13 10] , 
 and the difference is: 
 [7 2 5 0], 
 and the multiplication is: 
 [ 8 35 36 25]


In [109]:
np.dot(arr1,arr2) # combinaiton of the 2 arrays summed in 1 number 

np.int64(104)

NameError: name 'data' is not defined